### ISSUE TITLE
Theme MaterialNavigationDrawerTheme.Light.DarkActionBar partly dark

### ISSUE THREAD

**Issue by grote** [koesie10/MaterialNavigationDrawer#2]
Hi, thanks for maintaining this library! :)

I would like to use its MaterialNavigationDrawerTheme.Light.DarkActionBar theme, but on API 19 for example, many elements such as buttons still have the dark theme. Also, text color is white on white background. On API 22, there are no such issues.

This theme uses

``` xml
<item name="theme">@style/ThemeOverlay.AppCompat.Dark.ActionBar</item>
```

which might be part of the problem.

**Comment by koesie10** [comment]
Do you have an example app or screenshots of this behaviour? If I add a button to a fragment, it shows the correct button color on Genymotion API 19.

Also, if by text color is white on white background you mean the text color on the toolbar, this is expected behaviour as you would need to use a light actionbar.

**Comment by grote** [comment]
I'm using the standard emulator and get this behaviour only with API 19. But since you are not getting it with Genymotion, something else might be going on here.
There's a screenshot:
![api19](https://cloud.githubusercontent.com/assets/244947/7787214/cf4c3446-0253-11e5-8ea2-e244b612efae.png)
When I am adding

``` xml
<item name="theme">@style/ThemeOverlay.AppCompat.Light</item>
```

to my derived theme, it looks as it is supposed to, except that the ActionBar is Light.
Maybe the problem is due to me [switching the theme dynamically](https://github.com/grote/Liberario/blob/master/src/de/grobox/liberario/activities/MainActivity.java#L62) based on the users preference!?

**Comment by koesie10** [comment]
I don't think this is a problem of the library, as when you change the theme of the MainActivity from a MaterialNavigationDrawer theme to the normal AppCompat theme, it isn't solved directly:

``` java
if(Preferences.darkThemeEnabled(this)) {
    setTheme(R.style.AppTheme);
} else {
    setTheme(R.style.AppTheme_Light);
}
```

This doesn't solve anything and this is basically what the MaterialNavigationDrawer theme extends from. This might be a problem in your app or it might be a problem of appcompat.

**Comment by grote** [comment]
I'll have to dig deeper then :(
Thanks for looking into this so quickly! I'll close for now and post again if I think it has to do with this library.
